# Site settings
title: Software Engineering consultant
email: lukin.maksim@gmail.com
description: Experienced Ruby on Rails and Go developer specializing in scalable web applications
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://lukin.io"
twitter_username: lukin_io
github_username:  lukin-io
future: true

# Build settings
markdown: kramdown
permalink: /blog/:title

# Exclude files from Jekyll processing
exclude:
  - node_modules
  - package.json
  - package-lock.json
  - tailwind.config.js
  - postcss.config.js
  - assets/css/tailwind.scss

# Plugins
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
